@extends('layouts.app')
@section('title', 'Tanaman Pangan')
@section('body-class', 'dashboard-page force-light')
@push('styles')
<style>
.tp-toolbar{display:flex;align-items:center;justify-content:flex-start;margin-bottom:12px;gap:12px}
.tp-card{border-radius:16px;overflow:hidden}
.tp-card .card-header{padding:14px 18px;display:flex;align-items:center;justify-content:space-between;border-bottom:1px solid transparent;background:linear-gradient(90deg,#60a5fa,#3b82f6);color:#ffffff}
.tp-card .card-header .sub{font-size:13px;opacity:.9;color:#ffffff}
.tp-group{margin:14px 0 22px}
.tp-group .group-header{display:flex;align-items:center;justify-content:space-between;background:#dbeafe;color:#1e3a8a;border:1px solid #93c5fd;border-radius:12px 12px 0 0;padding:10px 12px}
.tp-group .badge{background:#2563eb;color:#fff;border-radius:9999px;width:24px;height:24px;display:inline-flex;align-items:center;justify-content:center;font-weight:700;margin-right:8px}
.tp-group .panel{border-radius:0 0 12px 12px;margin:0}
.tp-panel{margin:16px;border-radius:16px;padding:16px;border:1px solid #e5e7eb;background:#f8fafc}
.tp-panel .form-group{display:flex;flex-direction:column;gap:8px;margin-bottom:8px}
.tp-grid{display:grid;grid-template-columns:repeat(5,1fr);gap:12px}
.year-group{display:flex;flex-direction:column;gap:6px}
.year-label{font-size:12px;color:#1e3a8a;font-weight:600}
.tp-table{width:100%;border:1px solid #93c5fd !important;border-radius:12px;overflow:hidden;border-collapse:separate;border-spacing:0;table-layout:fixed}
.tp-table thead th{background:#dbeafe !important;color:#1e3a8a !important;font-weight:600;border-bottom:1px solid #93c5fd !important}
.tp-table.pangan thead th{background:#dbeafe !important;color:#1e3a8a !important}
.tp-table.sayur{border-color:#93c5fd !important}
.tp-table.sayur th,.tp-table.sayur td{border-color:#93c5fd !important}
.tp-table.sayur thead th{background:#dbeafe !important;color:#1e3a8a !important}
.tp-table.sayur thead .year{background:#dbeafe !important}
.tp-panel.sayur{background:#eff6ff;border-color:#bfdbfe}
.tp-panel.sayur .year-label{color:#1e3a8a}
.tp-table th,.tp-table td{border-bottom:1px solid #93c5fd !important;border-right:1px solid #93c5fd !important;padding:10px 12px}
.tp-table thead tr th:first-child{border-left:1px solid #93c5fd !important}
.tp-table tbody tr td:first-child{border-left:1px solid #93c5fd !important}
.tp-table tbody tr:last-child td{border-bottom:1px solid #93c5fd !important}
.tp-table th{font-weight:600;text-align:center}
.tp-table td,.tp-table th{padding:10px 12px}
.tp-table td:nth-child(1),.tp-table td:nth-child(2),.tp-table th:nth-child(1),.tp-table th:nth-child(2){text-align:left}
.tp-table tbody tr:nth-child(even){background:#f8fafc}
.tp-table tbody tr:hover{background:#f1f5f9}
.tp-table td:not(:nth-child(1)):not(:nth-child(2)){text-align:center}
.tp-table-wrap{border:1px solid #e5e7eb;border-radius:12px;overflow:hidden;background:#fff;box-shadow:0 1px 6px rgba(0,0,0,0.04)}
.edit-cell{border:1px solid #93c5fd;background:#ffffff;border-radius:10px;padding:8px 10px}
.btn-green{background:#2563eb;border-color:#2563eb;color:#fff}
.btn-lime{background:#84cc16;border-color:#84cc16;color:#fff}
.form-control{border:1px solid #93c5fd;background:#ffffff;border-radius:12px;padding:10px 12px}
.form-control:focus{outline:none;border-color:#2563eb;box-shadow:0 0 0 3px rgba(37,99,235,0.25)}
</style>
@endpush

@section('content')
    <div class="page active" id="tanaman-pangan-page">
      <div class="page-header"><h1>Data Tanaman Pangan & Sayuran</h1><p>Kabupaten Kolaka Utara Tahun 2019 - 2023</p></div>
      <div class="tp-toolbar"><div class="segmented"><button class="btn btn-primary btn-sm" id="tp-tab-pangan">Tanaman Pangan (Accordion)</button><button class="btn btn-outline btn-sm" id="tp-tab-sayur">Sayuran (Tabel)</button></div></div>
      <div id="tp-pangan">
        <div class="card tp-card theme-pangan">
          <div class="card-header"><div><h3>Ajukan Jenis Tanaman Baru</h3><div class="sub">Rekap luas panen, produksi, dan produktivitas 2019–2023</div></div><div class="card-actions"><button class="btn btn-outline btn-sm" id="tp-export"><i class="fas fa-download"></i> Export</button><button class="btn btn-outline btn-sm" id="tp-add-pangan"><i class="fas fa-plus"></i> Ajukan Jenis Tanaman</button></div></div>
          <div class="card-body">
            <div class="tp-panel pangan" id="tp-panel-pangan" style="display:none;">
              <div class="form-group"><label>Jenis Tanaman</label><input type="text" id="tp-jenis" class="form-control" placeholder="Contoh: Ubi Kayu"></div>
              <div class="form-group"><label>i. Luas Panen (ha)</label><div class="tp-grid"><div class="year-group"><div class="year-label">2019</div><input class="form-control" id="luas-2019" placeholder="0.00"></div><div class="year-group"><div class="year-label">2020</div><input class="form-control" id="luas-2020" placeholder="0.00"></div><div class="year-group"><div class="year-label">2021</div><input class="form-control" id="luas-2021" placeholder="0.00"></div><div class="year-group"><div class="year-label">2022</div><input class="form-control" id="luas-2022" placeholder="0.00"></div><div class="year-group"><div class="year-label">2023</div><input class="form-control" id="luas-2023" placeholder="0.00"></div></div></div>
              <div class="form-group"><label>ii. Produksi (ton)</label><div class="tp-grid"><div class="year-group"><div class="year-label">2019</div><input class="form-control" id="prod-2019" placeholder="0.00"></div><div class="year-group"><div class="year-label">2020</div><input class="form-control" id="prod-2020" placeholder="0.00"></div><div class="year-group"><div class="year-label">2021</div><input class="form-control" id="prod-2021" placeholder="0.00"></div><div class="year-group"><div class="year-label">2022</div><input class="form-control" id="prod-2022" placeholder="0.00"></div><div class="year-group"><div class="year-label">2023</div><input class="form-control" id="prod-2023" placeholder="0.00"></div></div></div>
              <div class="form-group"><label>iii. Produktivitas (ku/ha)</label><div class="tp-grid"><div class="year-group"><div class="year-label">2019</div><input class="form-control" id="pv-2019" placeholder="0.00"></div><div class="year-group"><div class="year-label">2020</div><input class="form-control" id="pv-2020" placeholder="0.00"></div><div class="year-group"><div class="year-label">2021</div><input class="form-control" id="pv-2021" placeholder="0.00"></div><div class="year-group"><div class="year-label">2022</div><input class="form-control" id="pv-2022" placeholder="0.00"></div><div class="year-group"><div class="year-label">2023</div><input class="form-control" id="pv-2023" placeholder="0.00"></div></div></div>
              <div style="display:flex;gap:8px;justify-content:flex-end"><button class="btn btn-secondary" id="tp-cancel-pangan">Batal</button><button class="btn btn-green" id="tp-save-pangan">Simpan Tanaman</button></div>
            </div>
            
            <div class="tp-table-wrap" id="tp-accordion"></div>
          </div>
        </div>
      </div>
      <div id="tp-sayur" style="display:none;">
        <div class="card tp-card theme-sayur">
          <div class="card-header"><div><h3>Ajukan Data Sayuran</h3><div class="sub">Luas tanaman dan produksi sayuran 2019–2023</div></div><div class="card-actions"><button class="btn btn-outline btn-sm" id="tp-export-sayur"><i class="fas fa-download"></i> Export</button><button class="btn btn-outline btn-sm" id="tp-add-sayur"><i class="fas fa-plus"></i> Ajukan Komoditas</button></div></div>
          <div class="card-body">
            <div class="tp-panel sayur" id="tp-panel-sayur" style="display:none;">
              <div class="form-group"><label>Jenis Komoditas</label><input type="text" id="syur-jenis" class="form-control" placeholder="Contoh: Tomat"></div>
              <div class="tp-grid">
                <div class="year-group"><div class="year-label">Tahun 2019</div><input class="form-control" id="syur-luas-2019" placeholder="Luas (ha)"><input class="form-control" id="syur-prod-2019" placeholder="Produksi (Kw)"></div>
                <div class="year-group"><div class="year-label">Tahun 2020</div><input class="form-control" id="syur-luas-2020" placeholder="Luas (ha)"><input class="form-control" id="syur-prod-2020" placeholder="Produksi (Kw)"></div>
                <div class="year-group"><div class="year-label">Tahun 2021</div><input class="form-control" id="syur-luas-2021" placeholder="Luas (ha)"><input class="form-control" id="syur-prod-2021" placeholder="Produksi (Kw)"></div>
                <div class="year-group"><div class="year-label">Tahun 2022</div><input class="form-control" id="syur-luas-2022" placeholder="Luas (ha)"><input class="form-control" id="syur-prod-2022" placeholder="Produksi (Kw)"></div>
                <div class="year-group"><div class="year-label">Tahun 2023</div><input class="form-control" id="syur-luas-2023" placeholder="Luas (ha)"><input class="form-control" id="syur-prod-2023" placeholder="Produksi (Kw)"></div>
              </div>
              <div style="display:flex;gap:8px;justify-content:flex-end;margin-top:8px"><button class="btn btn-secondary" id="tp-cancel-sayur">Batal</button><button class="btn btn-green" id="tp-save-sayur">Simpan</button></div>
            </div>
            <div class="tp-table-wrap"><table class="table table-compact tp-table sayur"><thead><tr><th rowspan="2">No</th><th rowspan="2">Jenis Komoditas</th><th class="year" colspan="2">Tahun 2019</th><th class="year" colspan="2">Tahun 2020</th><th class="year" colspan="2">Tahun 2021</th><th class="year" colspan="2">Tahun 2022</th><th class="year" colspan="2">Tahun 2023</th><th rowspan="2">Aksi</th></tr><tr><th>Luas Tanaman (ha)</th><th>Produksi (Kw)</th><th>Luas Tanaman (ha)</th><th>Produksi (Kw)</th><th>Luas Tanaman (ha)</th><th>Produksi (Kw)</th><th>Luas Tanaman (ha)</th><th>Produksi (Kw)</th><th>Luas Tanaman (ha)</th><th>Produksi (Kw)</th></tr></thead><tbody id="syur-tbody"></tbody></table></div>
          </div>
        </div>
      </div>
    </div>
@endsection

@push('scripts')
<script>
var csrfToken=document.querySelector('meta[name="csrf-token"]')?.content||'';window.USER_ROLE=document.body.dataset.userRole||'';var opdName='Dinas Pertanian Tanaman Pangan';var dinasId=(document.body.dataset.dinasId||'')||null;
var panganRaw=[];var panganGroups=[];
function groupPangan(data){var map={};(Array.isArray(data)?data:[]).forEach(function(r){var v=r.values||{};var g=v.group||'-';if(!map[g])map[g]=[];map[g].push({id:r.id,label:r.uraian,y2019:v.y2019||'',y2020:v.y2020||'',y2021:v.y2021||'',y2022:v.y2022||'',y2023:v.y2023||''});});return Object.keys(map).map(function(name){var rows=map[name].map(function(r,idx){return {id:r.id,no:idx+1,label:r.label,y2019:r.y2019,y2020:r.y2020,y2021:r.y2021,y2022:r.y2022,y2023:r.y2023}});return {name:name,rows:rows};});}
  function renderAccordion(){var wrap=document.getElementById('tp-accordion');if(!wrap)return;wrap.innerHTML=panganGroups.map(function(g,i){var header='<div class="group-header"><div><span class="badge">'+(i+1)+'</span>'+g.name+'</div><div><button class="btn btn-outline btn-sm" data-del="'+i+'" title="Hapus"><i class="fas fa-trash"></i></button></div></div>';var table='<div class="panel" style="background:#eff6ff;border-color:#bfdbfe"><div class="tp-table-wrap"><table class="table table-compact tp-table pangan"><thead><tr><th>No.</th><th>Jenis Tanaman</th><th>2019</th><th>2020</th><th>2021</th><th>2022</th><th>2023</th></tr></thead><tbody>'+g.rows.map(function(r){return '<tr data-group="'+i+'" data-row="'+(r.no-1)+'"><td>'+r.no+'</td><td>'+r.label+'</td><td class="c-2019">'+r.y2019+'</td><td class="c-2020">'+r.y2020+'</td><td class="c-2021">'+r.y2021+'</td><td class="c-2022">'+r.y2022+'</td><td class="c-2023">'+r.y2023+'</td></tr>'}).join('')+'</tbody></table></div></div>';return '<div class="tp-group">'+header+table+'</div>';}).join('');}
async function fetchPangan(){try{var res=await fetch('/tanaman-pangan/pangan',{headers:{'Accept':'application/json'}});var data=await res.json();panganRaw=data;panganGroups=groupPangan(data);renderAccordion();}catch(_){panganRaw=[];panganGroups=[];renderAccordion();}}
document.addEventListener('DOMContentLoaded',function(){fetchPangan()});
document.getElementById('tp-tab-pangan')?.addEventListener('click',function(){document.getElementById('tp-tab-pangan').classList.add('btn-primary');document.getElementById('tp-tab-pangan').classList.remove('btn-outline');document.getElementById('tp-tab-sayur').classList.add('btn-outline');document.getElementById('tp-tab-sayur').classList.remove('btn-primary');document.getElementById('tp-pangan').style.display='block';document.getElementById('tp-sayur').style.display='none';});
document.getElementById('tp-tab-sayur')?.addEventListener('click',function(){document.getElementById('tp-tab-sayur').classList.add('btn-primary');document.getElementById('tp-tab-sayur').classList.remove('btn-outline');document.getElementById('tp-tab-pangan').classList.add('btn-outline');document.getElementById('tp-tab-pangan').classList.remove('btn-primary');document.getElementById('tp-pangan').style.display='none';document.getElementById('tp-sayur').style.display='block';});
document.getElementById('tp-add-pangan')?.addEventListener('click',function(){var p=document.getElementById('tp-panel-pangan');var show=p.style.display==='none';p.style.display=show?'block':'none';this.innerHTML=show?'Tutup Form':'<i class="fas fa-plus"></i> Ajukan Jenis Tanaman';});
document.getElementById('tp-cancel-pangan')?.addEventListener('click',function(){document.getElementById('tp-panel-pangan').style.display='none';document.getElementById('tp-add-pangan').innerHTML='<i class="fas fa-plus"></i> Ajukan Jenis Tanaman';});
document.getElementById('tp-save-pangan')?.addEventListener('click',async function(){var jenis=document.getElementById('tp-jenis').value.trim();if(!jenis){Utils.showToast('Isi Jenis Tanaman','error');return;}var valsL={group:jenis,y2019:document.getElementById('luas-2019').value.trim(),y2020:document.getElementById('luas-2020').value.trim(),y2021:document.getElementById('luas-2021').value.trim(),y2022:document.getElementById('luas-2022').value.trim(),y2023:document.getElementById('luas-2023').value.trim()};var valsP={group:jenis,y2019:document.getElementById('prod-2019').value.trim(),y2020:document.getElementById('prod-2020').value.trim(),y2021:document.getElementById('prod-2021').value.trim(),y2022:document.getElementById('prod-2022').value.trim(),y2023:document.getElementById('prod-2023').value.trim()};var valsV={group:jenis,y2019:document.getElementById('pv-2019').value.trim(),y2020:document.getElementById('pv-2020').value.trim(),y2021:document.getElementById('pv-2021').value.trim(),y2022:document.getElementById('pv-2022').value.trim(),y2023:document.getElementById('pv-2023').value.trim()};var hasVal=(valsL.y2019||valsL.y2020||valsL.y2021||valsL.y2022||valsL.y2023||valsP.y2019||valsP.y2020||valsP.y2021||valsP.y2022||valsP.y2023||valsV.y2019||valsV.y2020||valsV.y2021||valsV.y2022||valsV.y2023);if(!hasVal){Utils.showToast('Isi minimal salah satu nilai tahun','error');return;}var isUser=(window.USER_ROLE==='user');try{if(!isUser){var r1=await fetch('/tanaman-pangan/pangan',{method:'POST',headers:{'Content-Type':'application/json','X-CSRF-TOKEN':csrfToken,'Accept':'application/json'},body:JSON.stringify({uraian:'Luas Panen (ha)',values:valsL})});if(!r1.ok){Utils.showToast('Gagal menyimpan','error');return;}var r2=await fetch('/tanaman-pangan/pangan',{method:'POST',headers:{'Content-Type':'application/json','X-CSRF-TOKEN':csrfToken,'Accept':'application/json'},body:JSON.stringify({uraian:'Produksi (ton)',values:valsP})});if(!r2.ok){Utils.showToast('Gagal menyimpan','error');return;}var r3=await fetch('/tanaman-pangan/pangan',{method:'POST',headers:{'Content-Type':'application/json','X-CSRF-TOKEN':csrfToken,'Accept':'application/json'},body:JSON.stringify({uraian:'Produktivitas (ku/ha)',values:valsV})});if(!r3.ok){Utils.showToast('Gagal menyimpan','error');return;}await fetchPangan();}
await fetch('/data-management/submit',{method:'POST',headers:{'Content-Type':'application/json','X-CSRF-TOKEN':csrfToken,'Accept':'application/json'},body:JSON.stringify({opd:opdName,dinas_id:dinasId,judul_data:'Tanaman Pangan '+jenis,file_path:'tanaman_pangan_kelompok',tahun_perencanaan:(new Date().getFullYear()).toString()})});
document.getElementById('tp-panel-pangan').style.display='none';document.getElementById('tp-add-pangan').textContent='+ Ajukan Jenis Tanaman';Utils.showToast('Data disimpan','success');}catch(e){Utils.showToast('Gagal menyimpan','error');}});
document.getElementById('tp-accordion')?.addEventListener('dblclick',function(e){var td=e.target.closest('td');if(!td)return;if(!td.classList.contains('c-2019')&&!td.classList.contains('c-2020')&&!td.classList.contains('c-2021')&&!td.classList.contains('c-2022')&&!td.classList.contains('c-2023'))return;var val=td.textContent;var controls='<div style="display:flex;align-items:center;gap:6px"><input class="edit-cell" value="'+val+'" style="flex:1"><button class="btn btn-green btn-xs ok"><i class="fas fa-check"></i></button><button class="btn btn-outline btn-xs cancel"><i class="fas fa-times"></i></button></div>';td.setAttribute('data-prev',val);td.innerHTML=controls;});
document.getElementById('tp-accordion')?.addEventListener('click',function(e){var delBtn=e.target.closest('[data-del]');if(delBtn){var i=parseInt(delBtn.getAttribute('data-del'),10);if(!isNaN(i)){Utils.confirm('Hapus kelompok ini?',{okText:'Hapus',cancelText:'Batal',variant:'danger'}).then(async function(yes){if(!yes)return;var isUser=(window.USER_ROLE==='user');if(isUser){Utils.showToast('Hanya admin yang bisa menghapus','error');return;}var groupName=panganGroups[i]?.name;var ids=(panganGroups[i]?.rows||[]).map(function(r){return r.id}).filter(Boolean);try{await Promise.all(ids.map(function(id){return fetch('/tanaman-pangan/pangan/'+id,{method:'DELETE',headers:{'X-CSRF-TOKEN':csrfToken,'Accept':'application/json'}})}));await fetchPangan();Utils.showToast('Kelompok dihapus','success');}catch(_){Utils.showToast('Gagal menghapus','error');}});}return;}var ok=e.target.closest('.ok');var cancel=e.target.closest('.cancel');if(!ok&&!cancel)return;var td=e.target.closest('td');var tr=td.closest('tr');var gi=parseInt(tr.dataset.group,10);var ri=parseInt(tr.dataset.row,10);var year=td.className.split('-')[1];var key='y'+year;if(ok){var val=td.querySelector('input').value;var row=panganGroups[gi].rows[ri];var isUser=(window.USER_ROLE==='user');if(isUser){Utils.showToast('Hanya admin yang bisa mengubah','error');td.textContent=td.getAttribute('data-prev');return;}td.textContent=val;var payload={uraian:row.label,values:{group:panganGroups[gi].name,y2019:row.y2019,y2020:row.y2020,y2021:row.y2021,y2022:row.y2022,y2023:row.y2023}};payload.values[key]=val;fetch('/tanaman-pangan/pangan/'+row.id,{method:'PUT',headers:{'Content-Type':'application/json','X-CSRF-TOKEN':csrfToken,'Accept':'application/json'},body:JSON.stringify(payload)}).then(async function(res){if(res.ok){await fetchPangan();Utils.showToast('Data diperbarui','success');}else{Utils.showToast('Gagal menyimpan','error');}}).catch(function(){Utils.showToast('Gagal menyimpan','error');});}else{td.textContent=td.getAttribute('data-prev');}});
var syurRows=[];
function renderSayur(){var tb=document.getElementById('syur-tbody');if(!tb)return;tb.innerHTML=syurRows.map(function(r,i){return '<tr data-row="'+r.no+'"><td>'+r.no+'</td><td class="c-jenis">'+r.jenis+'</td><td class="c-l2019">'+r.l2019+'</td><td class="c-p2019">'+r.p2019+'</td><td class="c-l2020">'+r.l2020+'</td><td class="c-p2020">'+r.p2020+'</td><td class="c-l2021">'+r.l2021+'</td><td class="c-p2021">'+r.p2021+'</td><td class="c-l2022">'+r.l2022+'</td><td class="c-p2022">'+r.p2022+'</td><td class="c-l2023">'+r.l2023+'</td><td class="c-p2023">'+r.p2023+'</td><td><button class="btn btn-outline btn-sm sy-edit-row action-btn"><i class="fas fa-pen"></i></button> <button class="btn btn-outline btn-sm action-btn" data-sy-del="'+i+'"><i class="fas fa-trash"></i></button></td></tr>';}).join('');}
async function fetchSayur(){try{var res=await fetch('/tanaman-pangan/sayur',{headers:{'Accept':'application/json'}});var data=await res.json();syurRows=(Array.isArray(data)?data:[]).map(function(r,i){var v=r.values||{};return {id:r.id,no:i+1,jenis:r.uraian,l2019:v.l2019||'',p2019:v.p2019||'',l2020:v.l2020||'',p2020:v.p2020||'',l2021:v.l2021||'',p2021:v.p2021||'',l2022:v.l2022||'',p2022:v.p2022||'',l2023:v.l2023||'',p2023:v.p2023||''};});renderSayur();}catch(_){syurRows=[];renderSayur();}}
document.addEventListener('DOMContentLoaded',function(){fetchSayur()});
document.getElementById('tp-add-sayur')?.addEventListener('click',function(){var p=document.getElementById('tp-panel-sayur');var show=p.style.display==='none';p.style.display=show?'block':'none';this.innerHTML=show?'Tutup Form':'<i class="fas fa-plus"></i> Ajukan Komoditas';});
document.getElementById('tp-cancel-sayur')?.addEventListener('click',function(){document.getElementById('tp-panel-sayur').style.display='none';document.getElementById('tp-add-sayur').innerHTML='<i class="fas fa-plus"></i> Ajukan Komoditas';});
document.getElementById('tp-save-sayur')?.addEventListener('click',async function(){var jenis=document.getElementById('syur-jenis').value.trim();if(!jenis){Utils.showToast('Isi Jenis Komoditas','error');return;}var vals={l2019:document.getElementById('syur-luas-2019').value.trim(),p2019:document.getElementById('syur-prod-2019').value.trim(),l2020:document.getElementById('syur-luas-2020').value.trim(),p2020:document.getElementById('syur-prod-2020').value.trim(),l2021:document.getElementById('syur-luas-2021').value.trim(),p2021:document.getElementById('syur-prod-2021').value.trim(),l2022:document.getElementById('syur-luas-2022').value.trim(),p2022:document.getElementById('syur-prod-2022').value.trim(),l2023:document.getElementById('syur-luas-2023').value.trim(),p2023:document.getElementById('syur-prod-2023').value.trim()};var hasVal=(vals.l2019||vals.p2019||vals.l2020||vals.p2020||vals.l2021||vals.p2021||vals.l2022||vals.p2022||vals.l2023||vals.p2023);if(!hasVal){Utils.showToast('Isi minimal salah satu nilai tahun','error');return;}var isUser=(window.USER_ROLE==='user');try{if(!isUser){var res=await fetch('/tanaman-pangan/sayur',{method:'POST',headers:{'Content-Type':'application/json','X-CSRF-TOKEN':csrfToken,'Accept':'application/json'},body:JSON.stringify({uraian:jenis,values:vals})});if(!res.ok){Utils.showToast('Gagal menyimpan','error');return;}await fetchSayur();}
await fetch('/data-management/submit',{method:'POST',headers:{'Content-Type':'application/json','X-CSRF-TOKEN':csrfToken,'Accept':'application/json'},body:JSON.stringify({opd:opdName,judul_data:'Sayuran '+jenis,file_path:'tanaman_pangan_sayur',tahun_perencanaan:(new Date().getFullYear()).toString()})});
document.getElementById('tp-panel-sayur').style.display='none';document.getElementById('tp-add-sayur').textContent='+ Ajukan Komoditas';Utils.showToast('Data disimpan','success');}catch(e){Utils.showToast('Gagal menyimpan','error');}});
document.getElementById('syur-tbody')?.addEventListener('dblclick',function(e){var td=e.target.closest('td');if(!td)return;if(!td.className.match(/^c\-/))return;var val=td.textContent;var controls='<div style="display:flex;align-items:center;gap:6px"><input class="edit-cell" value="'+val+'" style="flex:1"><button class="btn btn-green btn-xs ok"><i class="fas fa-check"></i></button><button class="btn btn-outline btn-xs cancel"><i class="fas fa-times"></i></button></div>';td.setAttribute('data-prev',val);td.innerHTML=controls;});
document.getElementById('syur-tbody')?.addEventListener('click',function(e){var ok=e.target.closest('.ok');var cancel=e.target.closest('.cancel');if(!ok&&!cancel)return;var td=e.target.closest('td');var tr=td.closest('tr');var idx=parseInt(tr.dataset.row,10)-1;var r=syurRows[idx];if(ok){var val=td.querySelector('input').value;var cls=td.className;switch(true){case /c-jenis/.test(cls): r.jenis=val; break;case /c-l2019/.test(cls): r.l2019=val; break;case /c-p2019/.test(cls): r.p2019=val; break;case /c-l2020/.test(cls): r.l2020=val; break;case /c-p2020/.test(cls): r.p2020=val; break;case /c-l2021/.test(cls): r.l2021=val; break;case /c-p2021/.test(cls): r.p2021=val; break;case /c-l2022/.test(cls): r.l2022=val; break;case /c-p2022/.test(cls): r.p2022=val; break;case /c-l2023/.test(cls): r.l2023=val; break;case /c-p2023/.test(cls): r.p2023=val; break;}var isUser=(window.USER_ROLE==='user');if(isUser){Utils.showToast('Hanya admin yang bisa mengubah','error');td.textContent=td.getAttribute('data-prev');return;}td.textContent=val;var payload={uraian:r.jenis,values:{l2019:r.l2019,p2019:r.p2019,l2020:r.l2020,p2020:r.p2020,l2021:r.l2021,p2021:r.p2021,l2022:r.l2022,p2022:r.p2022,l2023:r.l2023,p2023:r.p2023}};fetch('/tanaman-pangan/sayur/'+r.id,{method:'PUT',headers:{'Content-Type':'application/json','X-CSRF-TOKEN':csrfToken,'Accept':'application/json'},body:JSON.stringify(payload)}).then(async function(res){if(res.ok){await fetchSayur();Utils.showToast('Data diperbarui','success');}else{Utils.showToast('Gagal menyimpan','error');}}).catch(function(){Utils.showToast('Gagal menyimpan','error');});}else{td.textContent=td.getAttribute('data-prev');}});
document.getElementById('syur-tbody')?.addEventListener('click',function(e){var del=e.target.closest('[data-sy-del]');if(!del)return;var i=parseInt(del.getAttribute('data-sy-del'),10);Utils.confirm('Hapus baris ini?',{okText:'Hapus',cancelText:'Batal',variant:'danger'}).then(async function(yes){if(!yes)return;var isUser=(window.USER_ROLE==='user');if(isUser){Utils.showToast('Hanya admin yang bisa menghapus','error');return;}var id=syurRows[i]?.id;try{var res=await fetch('/tanaman-pangan/sayur/'+id,{method:'DELETE',headers:{'X-CSRF-TOKEN':csrfToken,'Accept':'application/json'}});if(res.ok){await fetchSayur();Utils.showToast('Baris dihapus','success');}else{Utils.showToast('Gagal menghapus','error');}}catch(_){Utils.showToast('Gagal menghapus','error');}});});
function exportCsv(filename, headers, rows){var csv=[headers].concat(rows).map(function(row){return row.map(function(v){var s=(''+(v==null?'':v)).replace(/"/g,'""');return '"'+s+'"';}).join(',');}).join('\n');var blob=new Blob([csv],{type:'text/csv;charset=utf-8;'});var url=URL.createObjectURL(blob);var a=document.createElement('a');a.href=url;a.download=filename;document.body.appendChild(a);a.click();document.body.removeChild(a);URL.revokeObjectURL(url);} 
document.getElementById('tp-export')?.addEventListener('click',function(){var headers=['Kelompok','No','Label','2019','2020','2021','2022','2023'];var rows=[];panganGroups.forEach(function(g){g.rows.forEach(function(r){rows.push([g.name,r.no,r.label,r.y2019,r.y2020,r.y2021,r.y2022,r.y2023])})});exportCsv('tanaman-pangan.csv',headers,rows)});
document.getElementById('tp-export-sayur')?.addEventListener('click',function(){var headers=['No','Jenis','L2019','P2019','L2020','P2020','L2021','P2021','L2022','P2022','L2023','P2023'];var rows=syurRows.map(function(r){return [r.no,r.jenis,r.l2019,r.p2019,r.l2020,r.p2020,r.l2021,r.p2021,r.l2022,r.p2022,r.l2023,r.p2023]});exportCsv('tanaman-sayur.csv',headers,rows)});
</script>
@endpush
